"""empty message

Revision ID: 19b6b39fe6e6
Revises: 3b4238e94c11
Create Date: 2022-10-18 04:55:36.026245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19b6b39fe6e6'
down_revision = '3b4238e94c11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
