"""First migration

Revision ID: 45f676bfea7c
Revises: d9e41f38793b
Create Date: 2022-10-19 08:32:02.044592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45f676bfea7c'
down_revision = 'd9e41f38793b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
