"""First migration

Revision ID: 5cd650c0fd57
Revises: 19b6b39fe6e6
Create Date: 2022-10-18 04:58:07.602245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cd650c0fd57'
down_revision = '19b6b39fe6e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
