"""First migration

Revision ID: 5ee05ad10f25
Revises: 90bc6cc424b5
Create Date: 2022-10-19 06:42:52.887477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ee05ad10f25'
down_revision = '90bc6cc424b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
