"""First migration2

Revision ID: 713fcd4ee46c
Revises: 5cd650c0fd57
Create Date: 2022-10-18 05:16:01.338245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '713fcd4ee46c'
down_revision = '5cd650c0fd57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
