"""First migration

Revision ID: 90bc6cc424b5
Revises: 7e4f5fb0b8f5
Create Date: 2022-10-19 06:12:14.135466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90bc6cc424b5'
down_revision = '7e4f5fb0b8f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
