"""First migration

Revision ID: d9e41f38793b
Revises: 5ee05ad10f25
Create Date: 2022-10-19 08:06:41.616420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9e41f38793b'
down_revision = '5ee05ad10f25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
